// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_calendars_id_ from "./routes/api/calendars/[id].ts";
import * as $api_calendars_index from "./routes/api/calendars/index.ts";
import * as $index from "./routes/index.tsx";
import * as $CalendarManager from "./islands/CalendarManager.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/calendars/[id].ts": $api_calendars_id_,
    "./routes/api/calendars/index.ts": $api_calendars_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CalendarManager.tsx": $CalendarManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
